services:
  - docker

language: python

python:
  - 3.6

cache: pip

install:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build

script:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api "make quality"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api "make detect_missing_migrations"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api "make migrate"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api "make test"

after_success:
  - pip install -U codecov
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api "coverage xml"
  - codecov

env:
  matrix:
    secure: mZAQR7e2soDYDssJGbyN0JMvHnisG3g601VsRa2v/736r9Xi3mJ5KDGBvrt9j69iANduSc31zFjmM3Acg3o/Ss2H4KX3HTCMRM8Y3W3t3oHxvlly4E0K1IRQDNX8ags/N/hjI9JxK9YcWud7uamnlB8HG1w/ziDfX6UbCda5oLphn1B7zUFM2Ui+72r0i3Su9nY0ZWUPQdaBGtcdenjKqsUQXvY3vEoHeSBLrduPQ0OoLQNvhyBR3fDHM3q/zP+1iK0vphT+RJVktOAJWfRN1LukdgSg2DL9txBg1GcP6C23o+wMdjqsDd+DWOo2pREua7qk0cPTGhuxdaXSUJH8gT2dX9yaafCWFbZ5fInx5A2XmB6mJGBPAz+q6BGmvIu/YNEXQPF9dYJArrIuNn2c9KCorANM9AaDf8+tROFx/6f3uGmE+IoZYIzV42lm5KaI82ofVMh5JqilWLHf3TSPWfekzmSsWluUYGj5TynITo3fga1rpotWFfrfvtZHpxdp1zfCp5V1AWUJG4GJ13yDJ/iLUvGtgKeI+mLiUUcImDT27JITmZFmnG2yQHFO7bQJhpGj+QU6mwmAjDkCaBX8/ClqtOOI59S2xGbtGOeXGKxZLjknt4EGz1VVS9rdy7Bzb0nHNvme5vxmryZO5MUl4OGsHQGY0i4IMJfA3kkBH3o=